apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-hackinsdn
  labels:
    app: helloworld-hackinsdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-hackinsdn
  template:
    metadata:
      name: helloworld-hackinsdn
      labels:
        app: helloworld-hackinsdn
    spec:
      containers:
      - name: helloworld-hackinsdn
        image: hackinsdn/helloworld:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-hackinsdn
  labels:
    app: helloworld-hackinsdn
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: http-helloworld-webserver
  selector:
    app: helloworld-hackinsdn
